name: api_check_in
description: A simple command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
dependencies: 
  crypto: ^3.0.1
  dotenv: ^3.0.0
  postgres: ^2.4.2
  shelf: ^1.2.0
  shelf_modular: ^1.0.0
